package eu.gricom.basic.functions;

import eu.gricom.basic.variableTypes.RealValue;

/**
 * RND Function.
 *
 * Description:
 *
 * The RND function returns a random number generated by the Java random number.
 *
 * (c) = 2021,.., by Andreas Grimm, Den Haag, The Netherlands
 */
public final class Rnd {

    /**
     * Private Constructor.
     */
    private Rnd() {
    }

    /**
     * Functions implemented here are similar to Statements with the difference
     * that they actually return a result to the caller of type Value. The method execute
     * triggers the function.
     *
     * @return Value the return message of the function
     */
    public static RealValue execute() {
            return new RealValue(Math.random());
    }
}
